on:
  issues:
    types: [opened]

jobs:
  label_issue_job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Label new issue
    steps:
      - id: label-new-issue
        uses: atgreen/gail-issue-labeler-action@master
        with:
          llm_api_key: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.OPENAI_KEY }}
