name: New Issue Notifier

on:
  issues:
    types: [opened]

jobs:
  log_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest GAIL release
        id: download-gail
        run: |
          # Get the latest release info
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/atgreen/gail/releases/latest)
          ASSET_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name == "gail-linux-x86_64") | .browser_download_url')

          # Download the asset
          wget "$ASSET_URL" -O gail-linux-x86_64
          chmod +x gail-linux-x86_64

          # Make it available for subsequent steps
          echo "GAIL_PATH=$(pwd)/gail-linux-x86_64" >> $GITHUB_ENV
          echo "asset_path=$(pwd)/gail-linux-x86_64" >> $GITHUB_OUTPUT

      - name: Run gail
        run: |
          echo "Issue title: {{ github.event.issue.title }}" > action-issue.txt
          echo "Issue number: ${{ github.event.issue.number }}" >> action-issue.txt
          echo "Issue body:" >> action-issue.txt
          echo "${{ github.event.issue.body }}" >> action-issue.txt
          cat action-issue | $GAIL_PATH --action "${{ github.repository_owner }}" "${{ github.event.repository.name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
